version: '3.8'


services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kinopoiskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5255742
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kinopoiskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5255742
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: